root: true

env:
  es6: true
  browser: true
  mocha: true

globals:
  chrome: true
  $: true

extends:
  - airbnb-base

parserOptions:
  sourceType: module
  parser: babel-eslint

rules:
  indent:
    - error
    - 4
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  # strict: 0
  max-len: [1, { code: 120 }]
  global-require: 0
  func-names: 0
  no-console: 0
  arrow-parens: 0
  no-alert: 0
  object-curly-newline: 0
  comma-dangle: ['error', 'only-multiline']
  no-param-reassign: 0
  space-before-function-paren: 0
  prefer-destructuring: 0
  prefer-promise-reject-errors: 0
  import/no-unresolved: [0, {commonjs: true, amd: true}]
  import/no-extraneous-dependencies: 0
  import/no-absolute-path: 0
  import/prefer-default-export: 0
